### ISSUE TITLE
Reset scene does not reset colors in the IHM

### ISSUE THREAD

**Issue by CharlesGueunet** [GuillaumeFavelier/blockbuilder#61]
Dear Guillaume,
Using the reset button reset the scene and the brush as expected, hela it does not reset the color widget in the IHM which could be misleadeing for the user.

Great project otherwise !

**Comment by GuillaumeFavelier** [comment]
Thanks for the great feedback and reporting the bug. I'll open a PR to fix that soon :ok_hand:
