### ISSUE TITLE
Black scene on 0.6.0

### ISSUE THREAD

**Issue by CharlesGueunet** [GuillaumeFavelier/blockbuilder#68]
Dear Guillaume,

I have installed blockbuilder using pip and forced the vtk version to be 9 (python 3.8.3)
On the current state, the scene is only a black screen.

Additionally, the color picker has a strange behavior as it seems to show a random color (not the one picked) except when the window is not focused, then it shows the right color.

C.

**Comment by GuillaumeFavelier** [comment]
Hi @CharlesGueunet thanks for reporting this. So you confirm that you did not have this with the previous version [`0.5.1`](https://github.com/GuillaumeFavelier/blockbuilder/releases/tag/0.5.1)?

Could you share a screenshot of your issue?

Also, to help me understand your situation, can you also try the following after installing [`scooby`](https://github.com/banesullivan/scooby):

```py
import scooby; scooby.Report(['vtk', 'qtpy', 'PyQt5', 'PySide2'])
```

*Note: I'll consider adding `scooby` as a requirement to help troubleshooting.*
